const mongoose = require('mongoose');
const dotenv = require('dotenv');
const User = require('./models/User');
const Product = require('./models/Product');
const Category = require('./models/Category');
const Order = require('./models/Order');
const Coupon = require('./models/Coupon');
const connectDB = require('./config/db');

const path = require('path');
dotenv.config({ path: path.join(__dirname, '.env') });
dotenv.config({ path: path.join(__dirname, '../.env') });

const seedData = async () => {
  try {
    await connectDB();

    console.log('Clearing old collections...');
    await User.deleteMany();
    await Product.deleteMany();
    await Category.deleteMany();
    await Order.deleteMany();
    await Coupon.deleteMany();

    console.log('Seeding Users...');
    // Create Admin User (Nabab Ali)
    const adminUser = await User.create({
      name: 'Nabab Ali',
      email: 'nabab9695ali@gmail.com',
      password: 'project1234',
      role: 'admin',
      phone: '+91 9695000000',
      avatar: '/nabab-ali.jpg',
      addresses: [
        {
          street: '124 Green Park Avenue',
          city: 'New Delhi',
          state: 'Delhi',
          postalCode: '110016',
          country: 'India',
          isDefault: true,
        },
      ],
    });

    // Create Customer Demo User
    const customerUser = await User.create({
      name: 'Priya Sharma',
      email: 'priya@example.com',
      password: 'password123',
      role: 'customer',
      phone: '+91 9876543210',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
      addresses: [
        {
          street: '45 Lotus Boulevard',
          city: 'Mumbai',
          state: 'Maharashtra',
          postalCode: '400001',
          country: 'India',
          isDefault: true,
        },
      ],
    });

    console.log('Seeding Categories...');
    const categoriesData = [
      {
        name: 'Electronics & Audio',
        slug: 'electronics-audio',
        icon: 'Headphones',
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80',
        description: 'Next-generation smart audio, solar-powered gadgets & energy-efficient electronics.',
        isFeatured: true,
      },
      {
        name: 'Eco Home & Living',
        slug: 'eco-home-living',
        icon: 'Home',
        image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=600&q=80',
        description: 'Sustainable home essentials, bamboo cutlery, natural decor and living.',
        isFeatured: true,
      },
      {
        name: 'Fashion & Apparel',
        slug: 'fashion-apparel',
        icon: 'Shirt',
        image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=600&q=80',
        description: '100% organic cotton, recycled fabrics and cruelty-free designer wear.',
        isFeatured: true,
      },
      {
        name: 'Organic Beauty & Wellness',
        slug: 'organic-beauty-wellness',
        icon: 'Sparkles',
        image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80',
        description: 'Chemical-free skincare, essential botanical oils and herbal wellness remedies.',
        isFeatured: true,
      },
      {
        name: 'Fitness & Outdoors',
        slug: 'fitness-outdoors',
        icon: 'Activity',
        image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
        description: 'Eco-friendly yoga mats, stainless steel flasks and lightweight gear.',
        isFeatured: true,
      },
    ];

    const categories = await Category.insertMany(categoriesData);

    console.log('Seeding Products...');
    const productsData = [
      {
        name: 'EcoSound Pro ANC Wireless Headphones',
        description: 'Engineered with recycled aerospace-grade aluminum and sustainable bamboo earcups. Features Active Noise Cancellation, 40-hour battery life, and crystal-clear Hi-Res Audio certification.',
        shortDescription: 'Sustainable bamboo earcups, 40h battery, active noise cancelling.',
        price: 8999,
        discountPrice: 6499,
        category: 'Electronics & Audio',
        brand: 'EcoSound',
        stock: 35,
        images: [
          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: true,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.9,
        numReviews: 48,
        specifications: [
          { key: 'Battery Life', value: '40 Hours' },
          { key: 'Connectivity', value: 'Bluetooth 5.3 & AUX' },
          { key: 'Weight', value: '240g' },
          { key: 'Materials', value: 'Recycled Aluminum & Organic Bamboo' },
        ],
        tags: ['headphones', 'bluetooth', 'audio', 'eco-friendly', 'anc'],
        seller: adminUser._id,
        reviews: [
          {
            user: customerUser._id,
            name: 'Priya Sharma',
            rating: 5,
            title: 'Incredible sound and eco-conscious build!',
            comment: 'The sound stage is rich and deep. Plus knowing it is crafted with recycled materials makes it even better.',
          },
        ],
      },
      {
        name: 'SolCharge 25000mAh Solar Power Bank',
        description: 'High efficiency monocrystalline solar panels with 65W Power Delivery fast charging. Water resistant, drop proof, and equipped with ultra-bright emergency LED torch.',
        shortDescription: 'Solar charging, 65W PD fast charge, waterproof rugged casing.',
        price: 4499,
        discountPrice: 2999,
        category: 'Electronics & Audio',
        brand: 'SolPower',
        stock: 45,
        images: [
          'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: true,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.8,
        numReviews: 32,
        specifications: [
          { key: 'Capacity', value: '25,000 mAh' },
          { key: 'Max Output', value: '65W USB-C PD' },
          { key: 'Solar Efficiency', value: '23.5%' },
        ],
        tags: ['solar', 'powerbank', 'travel', 'outdoor', 'gadgets'],
        seller: adminUser._id,
      },
      {
        name: 'PureBamboo 12-Piece Kitchen Utensil Set',
        description: 'Naturally antibacterial, 100% organic moso bamboo culinary utensils. Non-stick cookware friendly, heat resistant, zero plastic packaging.',
        shortDescription: '100% organic bamboo, heat resistant, non-toxic food safe.',
        price: 1999,
        discountPrice: 1299,
        category: 'Eco Home & Living',
        brand: 'BambooLiving',
        stock: 60,
        images: [
          'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: true,
        isBestSeller: false,
        isEcoChoice: true,
        rating: 4.7,
        numReviews: 24,
        specifications: [
          { key: 'Material', value: '100% Organic Moso Bamboo' },
          { key: 'Count', value: '12 Pieces + Holder' },
          { key: 'Dishwasher Safe', value: 'Handwash Recommended' },
        ],
        tags: ['kitchen', 'bamboo', 'utensils', 'sustainable', 'home'],
        seller: adminUser._id,
      },
      {
        name: 'Handcrafted Ceramic Aroma Diffuser & Humidifier',
        description: 'Artisanal ceramic ultrasonic diffuser that creates a soothing mist with soft ambient warm LED lighting. Auto shut-off safety protection.',
        shortDescription: 'Artisanal ceramic finish, ultrasonic misting, quiet whisper operation.',
        price: 3299,
        discountPrice: 2499,
        category: 'Eco Home & Living',
        brand: 'AuraZen',
        stock: 20,
        images: [
          'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: true,
        isBestSeller: true,
        isEcoChoice: false,
        rating: 4.9,
        numReviews: 53,
        specifications: [
          { key: 'Capacity', value: '300 ml' },
          { key: 'Coverage', value: 'Up to 350 sq ft' },
          { key: 'Timer Modes', value: '1H / 3H / 6H / Continuous' },
        ],
        tags: ['diffuser', 'aromatherapy', 'ceramic', 'wellness', 'decor'],
        seller: adminUser._id,
      },
      {
        name: 'Organic Raw Hemp Relaxed Fit Shirt',
        description: 'Breathable, naturally anti-microbial pure hemp fabric shirt. Gets softer with every wash while having 1/3rd the carbon footprint of conventional cotton.',
        shortDescription: '100% sustainable hemp fabric, relaxed modern fit, earth tone dyes.',
        price: 2899,
        discountPrice: 1999,
        category: 'Fashion & Apparel',
        brand: 'EarthThreads',
        stock: 40,
        images: [
          'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: true,
        isBestSeller: false,
        isEcoChoice: true,
        rating: 4.6,
        numReviews: 19,
        specifications: [
          { key: 'Fabric', value: '100% Organic Industrial Hemp' },
          { key: 'Fit', value: 'Modern Relaxed Fit' },
          { key: 'Care', value: 'Machine Wash Cold' },
        ],
        tags: ['shirt', 'hemp', 'fashion', 'men', 'organic'],
        seller: adminUser._id,
      },
      {
        name: 'Recycled Ocean Plastic Waterproof Backpack',
        description: 'Constructed from 40 certified recycled ocean plastic bottles. Features 16-inch padded laptop sleeve, hidden anti-theft pocket, and ergonomic back support.',
        shortDescription: 'Made from 40 recycled ocean bottles, water-resistant, 16" laptop sleeve.',
        price: 4999,
        discountPrice: 3499,
        category: 'Fashion & Apparel',
        brand: 'OceanRevive',
        stock: 28,
        images: [
          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: true,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.9,
        numReviews: 61,
        specifications: [
          { key: 'Capacity', value: '24 Liters' },
          { key: 'Laptop Compartment', value: 'Up to 16-inch MacBook / PC' },
          { key: 'Waterproof Rating', value: 'IPX4 Water Repellent' },
        ],
        tags: ['backpack', 'travel', 'bags', 'recycled', 'accessories'],
        seller: adminUser._id,
      },
      {
        name: 'Botanical Gold Face Elixir with Rosehip & Bakuchiol',
        description: 'Plant-based natural alternative to retinol. Infused with 24K nano-gold flakes, organic cold-pressed rosehip seed oil, and squalane for deep hydration.',
        shortDescription: '100% cold-pressed botanical oils, 24K gold flakes, retinol alternative.',
        price: 2499,
        discountPrice: 1799,
        category: 'Organic Beauty & Wellness',
        brand: 'VedicBotanics',
        stock: 50,
        images: [
          'https://images.unsplash.com/photo-1608248597359-006f15777717?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: true,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.9,
        numReviews: 89,
        specifications: [
          { key: 'Volume', value: '30 ml / 1.0 fl oz' },
          { key: 'Skin Type', value: 'All Skin Types & Sensitive' },
          { key: 'Certifications', value: 'Cruelty-Free, Vegan, Paraben-Free' },
        ],
        tags: ['skincare', 'face-oil', 'organic', 'beauty', 'serum'],
        seller: adminUser._id,
      },
      {
        name: 'Natural Tree Cork Non-Slip Yoga Mat',
        description: 'Harvested from regenerative cork oak trees and backed with natural tree rubber. Superior grip that enhances with sweat, naturally antimicrobial.',
        shortDescription: 'Natural organic tree cork, zero PVC or toxins, sweat-activated grip.',
        price: 3499,
        discountPrice: 2499,
        category: 'Fitness & Outdoors',
        brand: 'PranaFlow',
        stock: 30,
        images: [
          'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: true,
        isBestSeller: false,
        isEcoChoice: true,
        rating: 4.8,
        numReviews: 37,
        specifications: [
          { key: 'Dimensions', value: '72" x 26" (183cm x 66cm)' },
          { key: 'Thickness', value: '5mm Extra Cushioning' },
          { key: 'Material', value: 'Organic Cork & Natural Tree Rubber' },
        ],
        tags: ['yoga', 'fitness', 'mat', 'cork', 'exercise'],
        seller: adminUser._id,
      },
      {
        name: 'Thermal Double-Walled Stainless Steel Bottle 1000ml',
        description: 'Keeps beverages ice cold for 24 hours or piping hot for 12 hours. Zero condensation, BPA free, leakproof bamboo lid with sturdy carry handle.',
        shortDescription: '24h cold / 12h hot insulation, stainless steel 18/8, bamboo top.',
        price: 1499,
        discountPrice: 999,
        category: 'Fitness & Outdoors',
        brand: 'HydroEco',
        stock: 75,
        images: [
          'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1589365278144-c9e705f843ba?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: false,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.9,
        numReviews: 114,
        specifications: [
          { key: 'Capacity', value: '1000 ml (34 oz)' },
          { key: 'Steel Grade', value: 'Food-Grade 18/8 Pro Stainless Steel' },
          { key: 'Insulation', value: 'TempShield Double Wall Vacuum' },
        ],
        tags: ['waterbottle', 'flask', 'fitness', 'outdoor', 'reusable'],
        seller: adminUser._id,
      },
      {
        name: 'Smart Ambient Smart LED Plant Grow Light',
        description: 'Full spectrum LED lighting optimized for indoor house plants and herbs. App-controlled scheduling, sunrise-to-sunset dimming, ultra-low energy consumption.',
        shortDescription: 'Full-spectrum sunlight simulation, smart timer, energy efficient.',
        price: 3999,
        discountPrice: 2899,
        category: 'Electronics & Audio',
        brand: 'GreenTech',
        stock: 22,
        images: [
          'https://images.unsplash.com/photo-1530968033775-4c92998394fb?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: false,
        isBestSeller: false,
        isEcoChoice: true,
        rating: 4.7,
        numReviews: 16,
        specifications: [
          { key: 'Power', value: '35W LED (Equivalent to 150W)' },
          { key: 'Spectrum', value: '380nm - 780nm Full Sunlight' },
          { key: 'Mounting', value: 'Adjustable Telescopic Pole' },
        ],
        tags: ['plants', 'growlight', 'smarthome', 'indoor-garden', 'led'],
        seller: adminUser._id,
      },
      {
        name: 'Handcrafted Coconut Shell Bowl & Spoon Set',
        description: '100% natural and reclaimed coconut shells polished with organic virgin coconut oil. Perfect for smoothie bowls, buddha bowls, salads and acai.',
        shortDescription: 'Reclaimed coconut shells, zero chemicals, hand polished finish.',
        price: 899,
        discountPrice: 599,
        category: 'Eco Home & Living',
        brand: 'CocoNaturals',
        stock: 90,
        images: [
          'https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: false,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.8,
        numReviews: 42,
        specifications: [
          { key: 'Set', value: '4 Bowls + 4 Ebony Wood Spoons' },
          { key: 'Finish', value: 'Virgin Organic Coconut Oil' },
        ],
        tags: ['coconut', 'bowl', 'kitchen', 'smoothie', 'tableware'],
        seller: adminUser._id,
      },
      {
        name: 'SolarTrack Pro GPS Multi-Sport Smartwatch',
        description: 'Equipped with Power Glass solar charging lens that extends battery life up to 30 days. Features 24/7 heart-rate monitoring, SpO2 sensor, topo maps, and ocean-bound plastic bezel.',
        shortDescription: 'Solar charging glass, 30-day battery, GPS tracking, waterproof 50m.',
        price: 18999,
        discountPrice: 14499,
        category: 'Electronics & Audio',
        brand: 'SolarTrack',
        stock: 18,
        images: [
          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: true,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.9,
        numReviews: 78,
        specifications: [
          { key: 'Battery', value: 'Up to 30 Days with Solar' },
          { key: 'Water Rating', value: '5 ATM (50 Meters)' },
          { key: 'Display', value: '1.4" Sunlight-Visible MIP' },
        ],
        tags: ['smartwatch', 'solar', 'fitness', 'gps', 'wearables'],
        seller: adminUser._id,
      },
      {
        name: 'Natural Solid Bamboo 15W Qi Fast Wireless Charger',
        description: 'Crafted from sustainable FSC-certified solid moso bamboo. Qi fast wireless charging compatible with iPhone, Samsung, AirPods, and Qi devices with thermal protection.',
        shortDescription: '15W Qi fast charging, solid organic bamboo finish, LED indicator.',
        price: 1899,
        discountPrice: 1299,
        category: 'Electronics & Audio',
        brand: 'BambooTech',
        stock: 55,
        images: [
          'https://images.unsplash.com/photo-1622445262464-84b1456045b6?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1586816879360-004f5b0c51e3?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: false,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.7,
        numReviews: 35,
        specifications: [
          { key: 'Output', value: '15W / 10W / 7.5W / 5W' },
          { key: 'Material', value: '100% Solid Natural Bamboo' },
          { key: 'Input', value: 'USB-C Fast Charge' },
        ],
        tags: ['wireless-charger', 'bamboo', 'gadgets', 'iphone', 'desk'],
        seller: adminUser._id,
      },
      {
        name: 'EcoBoom 360° Recycled Waterproof Speaker',
        description: 'Immersive 360-degree punchy bass audio made from 100% recycled fabric and recycled plastics. IPX7 waterproof, floats in water, and delivers 20 hours of non-stop playtime.',
        shortDescription: 'IPX7 floating waterproof, 360° stereo bass, 20h playtime.',
        price: 3999,
        discountPrice: 2699,
        category: 'Electronics & Audio',
        brand: 'EcoBoom',
        stock: 40,
        images: [
          'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: true,
        isBestSeller: false,
        isEcoChoice: true,
        rating: 4.8,
        numReviews: 29,
        specifications: [
          { key: 'Playtime', value: '20 Hours' },
          { key: 'Waterproof', value: 'IPX7 Submersible' },
          { key: 'Bluetooth', value: 'Version 5.3' },
        ],
        tags: ['speaker', 'bluetooth', 'audio', 'waterproof', 'travel'],
        seller: adminUser._id,
      },
      {
        name: 'Solar Camp Lantern with Emergency USB Power Hub',
        description: 'Collapsible dual solar and USB rechargeable camping lantern with 3 light modes: Warm reading glow, 500 lumens bright floodlight, and SOS strobe.',
        shortDescription: 'Dual solar/USB charge, 500 lumens, collapsible silicone body.',
        price: 1799,
        discountPrice: 1199,
        category: 'Electronics & Audio',
        brand: 'SolPower',
        stock: 65,
        images: [
          'https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: false,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.8,
        numReviews: 44,
        specifications: [
          { key: 'Brightness', value: '500 Lumens Max' },
          { key: 'Battery', value: '4400 mAh with Powerbank Mode' },
          { key: 'Weight', value: '280g' },
        ],
        tags: ['lantern', 'solar', 'camping', 'outdoor', 'light'],
        seller: adminUser._id,
      },
      {
        name: 'Hand-Poured Soy Wax & Cedarwood Scented Candle',
        description: '100% natural organic soy wax infused with pure cedarwood, wild amber, and sandalwood essential oils. Features a crackling natural wood wick with 55+ hours clean burn time.',
        shortDescription: '100% soy wax, crackling wood wick, 55h burn time, zero toxins.',
        price: 1299,
        discountPrice: 899,
        category: 'Eco Home & Living',
        brand: 'AuraZen',
        stock: 80,
        images: [
          'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1572726729207-a78d6feb18d7?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: false,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.9,
        numReviews: 63,
        specifications: [
          { key: 'Wax Type', value: '100% Organic Soy' },
          { key: 'Burn Time', value: '55 - 60 Hours' },
          { key: 'Wick', value: 'FSC Certified Wood Wick' },
        ],
        tags: ['candle', 'aromatherapy', 'decor', 'cedarwood', 'soywax'],
        seller: adminUser._id,
      },
      {
        name: 'Pure Handcrafted Ayurvedic Copper Water Dispenser 5L',
        description: 'Hammered pure copper 5-liter water pot with leakproof brass tap. Infuses water with natural copper ions according to traditional Ayurvedic health principles.',
        shortDescription: '100% pure hammered copper, 5L capacity, brass faucet, Ayurvedic.',
        price: 4299,
        discountPrice: 3199,
        category: 'Eco Home & Living',
        brand: 'VedicLiving',
        stock: 25,
        images: [
          'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1616401784845-180882ba9ba8?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: true,
        isBestSeller: false,
        isEcoChoice: true,
        rating: 4.9,
        numReviews: 31,
        specifications: [
          { key: 'Capacity', value: '5 Liters' },
          { key: 'Material', value: '99.9% Pure Certified Copper' },
          { key: 'Tap', value: 'Heavy Duty Solid Brass' },
        ],
        tags: ['copper', 'water', 'ayurveda', 'kitchen', 'wellness'],
        seller: adminUser._id,
      },
      {
        name: 'Organic French Flax Linen Bedding Duvet Set',
        description: 'Woven from 100% certified Normandy French flax linen. Highly breathable, thermoregulating in winter and summer, and pre-washed for cloud-like softness.',
        shortDescription: '100% French flax linen, pre-washed softness, hypoallergenic.',
        price: 8499,
        discountPrice: 5999,
        category: 'Eco Home & Living',
        brand: 'PureLoom',
        stock: 20,
        images: [
          'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: true,
        isBestSeller: false,
        isEcoChoice: true,
        rating: 4.9,
        numReviews: 47,
        specifications: [
          { key: 'Fabric', value: '100% Natural French Flax' },
          { key: 'Includes', value: '1 Queen Duvet Cover + 2 Pillowcases' },
          { key: 'Care', value: 'Machine Wash Gentle' },
        ],
        tags: ['bedding', 'linen', 'home', 'duvet', 'bedroom'],
        seller: adminUser._id,
      },
      {
        name: 'Reclaimed Solid Teak Wood End-Grain Cutting Board',
        description: 'Handcrafted from reclaimed teak wood scraps with natural food-safe mineral oil seasoning. Gentle on knife blades with juice groove and side handles.',
        shortDescription: 'Reclaimed plantation teak wood, end-grain knife friendly, juice groove.',
        price: 2499,
        discountPrice: 1799,
        category: 'Eco Home & Living',
        brand: 'EarthWood',
        stock: 35,
        images: [
          'https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: false,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.8,
        numReviews: 38,
        specifications: [
          { key: 'Dimensions', value: '16" x 12" x 1.5"' },
          { key: 'Wood', value: '100% Reclaimed Teak' },
        ],
        tags: ['cuttingboard', 'teak', 'kitchen', 'cooking', 'wood'],
        seller: adminUser._id,
      },
      {
        name: 'Zero-Waste Organic Bamboo Toothbrushes (Pack of 8)',
        description: 'Plant-based biodegradable bamboo handles with charcoal-infused soft bristles. 100% compostable packaging with distinct colored base markers for the entire family.',
        shortDescription: 'Pack of 8 organic bamboo toothbrushes with charcoal soft bristles.',
        price: 699,
        discountPrice: 449,
        category: 'Eco Home & Living',
        brand: 'BambooLiving',
        stock: 120,
        images: [
          'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: false,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.9,
        numReviews: 142,
        specifications: [
          { key: 'Count', value: '8 Toothbrushes' },
          { key: 'Bristles', value: 'Charcoal Infused Soft' },
          { key: 'Packaging', value: '100% Recycled Kraft Paper' },
        ],
        tags: ['toothbrush', 'bamboo', 'bathroom', 'zero-waste', 'hygiene'],
        seller: adminUser._id,
      },
      {
        name: 'Reusable Organic Beeswax Food Wraps (Pack of 5)',
        description: 'Natural alternative to plastic cling wrap. Infused with organic beeswax, jojoba oil, and tree resin on GOTS organic cotton. Washable, reusable up to 1 year.',
        shortDescription: 'Pack of 5 multi-size beeswax wraps, reusable, washable, zero plastic.',
        price: 999,
        discountPrice: 699,
        category: 'Eco Home & Living',
        brand: 'EcoWrap',
        stock: 85,
        images: [
          'https://images.unsplash.com/photo-1610557892470-55d9e80c0bce?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: false,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.7,
        numReviews: 54,
        specifications: [
          { key: 'Sizes', value: '2 Small, 2 Medium, 1 Large' },
          { key: 'Lifespan', value: '120 - 150 Washes' },
        ],
        tags: ['beeswax', 'foodwrap', 'kitchen', 'plastic-free', 'storage'],
        seller: adminUser._id,
      },
      {
        name: 'Handwoven Natural Jute Storage & Laundry Basket',
        description: 'Braided by skilled artisan cooperatives from 100% natural golden jute fibers. Reinforced vegan leather handles, foldable design for laundry, toys, or planters.',
        shortDescription: 'Handwoven 100% natural jute basket, vegan leather handles.',
        price: 1599,
        discountPrice: 1099,
        category: 'Eco Home & Living',
        brand: 'ArtisanCrafts',
        stock: 50,
        images: [
          'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: false,
        isBestSeller: false,
        isEcoChoice: true,
        rating: 4.8,
        numReviews: 26,
        specifications: [
          { key: 'Dimensions', value: '18" Height x 16" Diameter' },
          { key: 'Material', value: '100% Natural Golden Jute' },
        ],
        tags: ['basket', 'jute', 'laundry', 'decor', 'storage'],
        seller: adminUser._id,
      },
      {
        name: 'Vegan Apple-Skin Leather Minimalist RFID Wallet',
        description: 'Innovative bio-leather crafted from upcycled industrial apple waste from the juice industry. Features RFID blocking security, 8 card slots, and currency pocket.',
        shortDescription: 'Crafted from upcycled apple peel bio-leather, RFID protection.',
        price: 2499,
        discountPrice: 1699,
        category: 'Fashion & Apparel',
        brand: 'AppleSkin Studio',
        stock: 45,
        images: [
          'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: true,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.9,
        numReviews: 67,
        specifications: [
          { key: 'Material', value: 'AppleSkin Bio-Leather (50% Apple waste)' },
          { key: 'Capacity', value: '8 Cards + Cash Pocket' },
          { key: 'Security', value: '13.56 MHz RFID Shielding' },
        ],
        tags: ['wallet', 'vegan-leather', 'accessories', 'men', 'rfid'],
        seller: adminUser._id,
      },
      {
        name: 'Heavyweight Organic French Terry Unisex Hoodie',
        description: '450 GSM pure GOTS certified organic cotton loopback French terry. Custom dyed with non-toxic botanical pigments with double-lined hood and zero microplastics.',
        shortDescription: '450 GSM 100% organic cotton French terry, oversized relaxed fit.',
        price: 3699,
        discountPrice: 2499,
        category: 'Fashion & Apparel',
        brand: 'EarthThreads',
        stock: 35,
        images: [
          'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: true,
        isBestSeller: false,
        isEcoChoice: true,
        rating: 4.8,
        numReviews: 33,
        specifications: [
          { key: 'Fabric', value: '100% GOTS Organic Cotton (450 GSM)' },
          { key: 'Fit', value: 'Unisex Relaxed Streetwear' },
        ],
        tags: ['hoodie', 'organic-cotton', 'streetwear', 'fashion', 'warm'],
        seller: adminUser._id,
      },
      {
        name: 'Natural Tree Cork Belt with Antique Brass Buckle',
        description: 'Harvested from sustainably managed Mediterranean cork oak forests. Waterproof, tear-proof, soft to the touch, and 100% cruelty-free leather alternative.',
        shortDescription: 'Organic Portuguese tree cork, reversible, nickel-free buckle.',
        price: 1899,
        discountPrice: 1299,
        category: 'Fashion & Apparel',
        brand: 'PranaFlow',
        stock: 40,
        images: [
          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: false,
        isBestSeller: false,
        isEcoChoice: true,
        rating: 4.7,
        numReviews: 21,
        specifications: [
          { key: 'Material', value: '100% Natural Cork Fabric' },
          { key: 'Buckle', value: 'Antiqued Brass (Nickel-Free)' },
        ],
        tags: ['belt', 'cork', 'accessories', 'vegan', 'sustainable'],
        seller: adminUser._id,
      },
      {
        name: 'Ocean-Recycled Polarized Classic Wayfarer Sunglasses',
        description: 'Frames molded from 100% certified recovered ocean fishing nets. Equipped with Category 3 polarized UV400 lenses with anti-scratch and anti-glare coatings.',
        shortDescription: 'Made from recycled fishing nets, UV400 polarized optics, zero plastic.',
        price: 2999,
        discountPrice: 1999,
        category: 'Fashion & Apparel',
        brand: 'OceanRevive',
        stock: 50,
        images: [
          'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: true,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.9,
        numReviews: 52,
        specifications: [
          { key: 'Lenses', value: 'Polarized TAC UV400' },
          { key: 'Frame Material', value: '100% Recycled Ghost Fishing Nets' },
        ],
        tags: ['sunglasses', 'polarized', 'ocean-plastic', 'fashion', 'eyewear'],
        seller: adminUser._id,
      },
      {
        name: 'Ultra-Soft Bamboo Fiber Crew Socks (Pack of 5)',
        description: 'Naturally antibacterial and moisture-wicking organic bamboo viscose socks. Seamless toe closure with reinforced heel support for all-day odor-free comfort.',
        shortDescription: 'Pack of 5 organic bamboo socks, odor-resistant, seamless toe.',
        price: 899,
        discountPrice: 599,
        category: 'Fashion & Apparel',
        brand: 'BambooLiving',
        stock: 95,
        images: [
          'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: false,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.8,
        numReviews: 76,
        specifications: [
          { key: 'Composition', value: '80% Bamboo Viscose, 18% Recycled Poly, 2% Spandex' },
          { key: 'Count', value: '5 Pairs' },
        ],
        tags: ['socks', 'bamboo', 'comfort', 'apparel', 'essentials'],
        seller: adminUser._id,
      },
      {
        name: 'Organic Cotton Canvas Everyday Low Sneakers',
        description: 'Stitched with 100% certified organic cotton canvas with natural vulcanized tree rubber soles and removable natural cork insoles for cushioned arch support.',
        shortDescription: '100% organic cotton canvas, natural tree rubber soles, cork footbed.',
        price: 4499,
        discountPrice: 3299,
        category: 'Fashion & Apparel',
        brand: 'EarthThreads',
        stock: 28,
        images: [
          'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: true,
        isBestSeller: false,
        isEcoChoice: true,
        rating: 4.8,
        numReviews: 39,
        specifications: [
          { key: 'Upper', value: '100% Heavyweight Organic Cotton Canvas' },
          { key: 'Sole', value: 'Natural Wild Tree Latex Rubber' },
        ],
        tags: ['sneakers', 'shoes', 'footwear', 'organic', 'casual'],
        seller: adminUser._id,
      },
      {
        name: 'Kumkumadi 24K Gold Ayurvedic Miracle Face Oil',
        description: 'Authentic 16-herb classical Ayurvedic formula with pure Kashmiri saffron strands, sandalwood, and 24K nano gold leaves. Brightens skin tone and reduces pigmentation.',
        shortDescription: 'Authentic Kashmiri saffron & 24K gold flakes, Ayurvedic miracle elixir.',
        price: 2999,
        discountPrice: 2199,
        category: 'Organic Beauty & Wellness',
        brand: 'VedicBotanics',
        stock: 45,
        images: [
          'https://images.unsplash.com/photo-1608248597359-006f15777717?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: true,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.9,
        numReviews: 95,
        specifications: [
          { key: 'Key Ingredients', value: 'Kashmiri Mogra Saffron, Red Sandalwood, 24K Gold' },
          { key: 'Size', value: '30 ml Glass Dropper Bottle' },
        ],
        tags: ['kumkumadi', 'ayurveda', 'face-oil', 'saffron', 'gold'],
        seller: adminUser._id,
      },
      {
        name: 'Activated Bamboo Charcoal Detox Purifying Cleanser',
        description: 'Sulfate-free foaming cleanser with activated moso bamboo charcoal, tea tree oil, and organic aloe vera. Draws out deep pore impurities without stripping moisture.',
        shortDescription: 'Activated bamboo charcoal & tea tree, sulfate-free deep detox.',
        price: 899,
        discountPrice: 599,
        category: 'Organic Beauty & Wellness',
        brand: 'VedicBotanics',
        stock: 70,
        images: [
          'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1608248597359-006f15777717?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: false,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.8,
        numReviews: 48,
        specifications: [
          { key: 'Volume', value: '150 ml' },
          { key: 'Skin Type', value: 'Oily, Combination & Acne-Prone' },
        ],
        tags: ['facewash', 'charcoal', 'skincare', 'cleaner', 'organic'],
        seller: adminUser._id,
      },
      {
        name: '100% Pure Cold-Pressed Sweet Almond Hair & Body Oil',
        description: 'Single-origin, unrefined sweet almond oil extracted through traditional wooden expeller (Kachi Ghani). Packed with natural Vitamin E, magnesium, and essential fatty acids.',
        shortDescription: 'Cold-pressed wooden expeller, 100% pure sweet almond, Vitamin E.',
        price: 1199,
        discountPrice: 799,
        category: 'Organic Beauty & Wellness',
        brand: 'VedicBotanics',
        stock: 60,
        images: [
          'https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1608248597359-006f15777717?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: false,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.9,
        numReviews: 61,
        specifications: [
          { key: 'Volume', value: '200 ml' },
          { key: 'Extraction', value: 'Cold-Pressed Unrefined' },
        ],
        tags: ['hairoil', 'almond-oil', 'massage', 'wellness', 'bodycare'],
        seller: adminUser._id,
      },
      {
        name: 'Natural Tree Latex Resistance Bands Set (5 Strengths)',
        description: 'Made from 100% natural biodegradable Malaysian tree latex rubber with zero synthetic TPE or PVC. Includes 5 resistance levels from Extra Light to Extra Heavy with travel pouch.',
        shortDescription: '100% natural tree latex, 5 resistance levels, zero synthetic TPE.',
        price: 1499,
        discountPrice: 999,
        category: 'Fitness & Outdoors',
        brand: 'PranaFlow',
        stock: 50,
        images: [
          'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: false,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.8,
        numReviews: 43,
        specifications: [
          { key: 'Set', value: '5 Loop Bands (10 lbs to 50 lbs)' },
          { key: 'Material', value: '100% Pure Natural Tree Latex' },
        ],
        tags: ['resistance-bands', 'fitness', 'workout', 'gym', 'calisthenics'],
        seller: adminUser._id,
      },
      {
        name: 'Heavy-Duty 100% Organic Hemp Gym & Travel Duffel',
        description: 'Water-resistant, naturally mold-resistant pure industrial hemp canvas duffel. Includes ventilated shoe compartment, padded shoulder strap, and waterproof inner lining.',
        shortDescription: 'Pure hemp canvas, shoe compartment, 42L capacity, indestructible.',
        price: 4999,
        discountPrice: 3499,
        category: 'Fitness & Outdoors',
        brand: 'EarthThreads',
        stock: 22,
        images: [
          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: true,
        isBestSeller: false,
        isEcoChoice: true,
        rating: 4.9,
        numReviews: 28,
        specifications: [
          { key: 'Capacity', value: '42 Liters' },
          { key: 'Fabric', value: '100% Heavy Hemp Canvas (550 GSM)' },
          { key: 'Zippers', value: 'YKK Recycled Metal Zippers' },
        ],
        tags: ['duffel', 'gym-bag', 'hemp', 'travel', 'luggage'],
        seller: adminUser._id,
      },
      {
        name: 'Featherlight Titanium Camping Cutlery 3-Piece Set',
        description: 'Ultralight, rustproof aerospace Grade 1 titanium knife, fork, and spoon set with carabiner clip and recycled canvas pouch. Weighs only 48 grams total.',
        shortDescription: 'Grade 1 titanium, ultra-lightweight 48g, rust-proof, carabiner clip.',
        price: 1699,
        discountPrice: 1199,
        category: 'Fitness & Outdoors',
        brand: 'HydroEco',
        stock: 40,
        images: [
          'https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80',
        ],
        isFeatured: false,
        isBestSeller: true,
        isEcoChoice: true,
        rating: 4.9,
        numReviews: 36,
        specifications: [
          { key: 'Weight', value: '48 Grams Total' },
          { key: 'Material', value: '100% Pure Grade 1 Titanium' },
        ],
        tags: ['titanium', 'cutlery', 'camping', 'backpacking', 'outdoor'],
        seller: adminUser._id,
      },
    ];

    const productsWithSlugs = productsData.map(p => ({
      ...p,
      slug: p.name.toLowerCase().replace(/[^\w ]+/g, '').replace(/ +/g, '-') + '-' + Math.random().toString(36).substring(2, 6)
    }));

    const products = await Product.insertMany(productsWithSlugs);

    console.log('Seeding Coupons...');
    const couponsData = [
      {
        code: 'ECO20',
        discountPercent: 20,
        minOrderAmount: 999,
        maxDiscount: 2000,
        expiresAt: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
        isActive: true,
      },
      {
        code: 'NABAB50',
        discountPercent: 50,
        minOrderAmount: 1499,
        maxDiscount: 1500,
        expiresAt: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
        isActive: true,
      },
      {
        code: 'WELCOME10',
        discountPercent: 10,
        minOrderAmount: 499,
        maxDiscount: 1000,
        expiresAt: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
        isActive: true,
      },
    ];

    await Coupon.insertMany(couponsData);

    console.log('Seeding Demo Order...');
    await Order.create({
      user: customerUser._id,
      orderNumber: 'ECM-WELCOME-9821',
      orderItems: [
        {
          name: products[0].name,
          qty: 1,
          image: products[0].images[0],
          price: products[0].discountPrice || products[0].price,
          product: products[0]._id,
        },
        {
          name: products[2].name,
          qty: 1,
          image: products[2].images[0],
          price: products[2].discountPrice || products[2].price,
          product: products[2]._id,
        },
      ],
      shippingAddress: {
        fullName: 'Priya Sharma',
        phone: '+91 9876543210',
        street: '45 Lotus Boulevard',
        city: 'Mumbai',
        state: 'Maharashtra',
        postalCode: '400001',
        country: 'India',
      },
      paymentMethod: 'UPI',
      itemsPrice: 7798,
      taxPrice: 389,
      shippingPrice: 0,
      discountAmount: 1000,
      couponCode: 'ECO20',
      totalPrice: 7187,
      isPaid: true,
      paidAt: Date.now(),
      status: 'Shipped',
      trackingHistory: [
        {
          status: 'Order Placed',
          message: 'Order placed and payment received via UPI',
          timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
        },
        {
          status: 'Processing',
          message: 'Packed and prepared at Central Eco Hub Delhi',
          timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000),
        },
        {
          status: 'Shipped',
          message: 'Handed over to Express Courier (Tracking: BLUEDART-882193)',
          timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
        },
      ],
    });

    console.log('Seeding Completed Successfully!');
    process.exit();
  } catch (error) {
    console.error(`Seeder Error: ${error.message}`);
    process.exit(1);
  }
};

seedData();
